export {
  AuthorTag,
  CampusTagNormal,
  CampusTagVerified,
  IconAt,
  IconAvatarRing,
  IconBack,
  IconCampusBadge,
  IconChevronDown,
  IconComment,
  IconDot,
  IconFollow,
  IconGallery,
  IconHeartFill,
  IconHeartOutline,
  IconImageInput,
  IconLocation,
  IconMore,
  IconMountain,
  IconReply,
  IconShare,
  IconSmile,
} from './generated';