[flyway]
locations = ["filesystem:./database/flyway/sql"]
validateMigrationNaming = true
placeholderPrefix = "#["
placeholderSuffix = "]"

[flyway.placeholders]
admin-openid = "admin-default-openid-change-me"
admin-nickname = "系统管理员"
admin-password-hash = ".20cQQubK3.HZWzG3YB1tlRy.fqvM/BG"
