/**
 * Likes Store Mock 数据（mock 模式专用）。
 *
 * 隔离原则：本文件仅被 stores/likes.ts 的 useMock() 分支引用，
 * real 模式（apiMode=real）不会读取其中的任何 mock 用户/会话 ID。
 * 类型经 import type 引用（编译期擦除，无运行时循环依赖）。
 */
import type { HeartSignal, LikeRecord, VisitorRecord } from "../likes";

/** Mock 当前用户 ID（模拟当前登录用户身份，仅 mock 分支使用） */
export const MOCK_CURRENT_USER_ID = "user-1001";

/* ========== Mock 数据 ========== */

export const mockLikes: LikeRecord[] = [
  {
    id: "like-1",
    userId: "user-2001",
    name: "林夕",
    avatar: "/static/default-avatar.png",
    headline: "中山大学 · 大二 · 喜欢电影和咖啡",
    likedAt: "2026-05-20T14:30:00Z",
  },
  {
    id: "like-2",
    userId: "user-2002",
    name: "陈默",
    avatar: "/static/default-avatar.png",
    headline: "华南理工 · 大三 · 自习搭子",
    likedAt: "2026-05-19T10:15:00Z",
  },
];

export const mockLikedBy: LikeRecord[] = [
  {
    id: "like-3",
    userId: "user-2003",
    name: "苏晴",
    avatar: "/static/assets/images/avatars/avatar-28.jpg",
    headline: "中山大学 · 大一 · 摄影爱好者",
    likedAt: "2026-05-20T16:45:00Z",
    verificationBadgeLevel: "school",
  },
  {
    id: "like-4",
    userId: "user-2004",
    name: "周然",
    avatar: "/static/assets/images/avatars/avatar-29.jpg",
    headline: "华南理工 · 研一 · 喜欢夜跑",
    likedAt: "2026-05-18T09:20:00Z",
    verificationBadgeLevel: "email",
  },
  {
    id: "like-5",
    userId: "user-2006",
    name: "叶知秋",
    avatar: "/static/assets/images/avatars/avatar-30.jpg",
    headline: "暨南大学 · 大二 · 文学系",
    likedAt: "2026-05-17T20:10:00Z",
  },
  {
    id: "like-6",
    userId: "user-2007",
    name: "沈星河",
    avatar: "/static/assets/images/avatars/avatar-31.jpg",
    headline: "广东工业 · 大三 · 篮球队",
    likedAt: "2026-05-16T14:00:00Z",
    verificationBadgeLevel: "idcard",
  },
  {
    id: "like-7",
    userId: "user-2200",
    name: "叶知秋",
    avatar: "/static/assets/images/avatars/avatar-28.jpg",
    headline: "北京大学 · 大1 · 自习搭子",
    likedAt: "2026-05-15T10:00:00Z",
    verificationBadgeLevel: "school"
  },
  {
    id: "like-8",
    userId: "user-2201",
    name: "沈星河",
    avatar: "/static/assets/images/avatars/avatar-29.jpg",
    headline: "复旦大学 · 大2 · 骑行党",
    likedAt: "2026-05-14T11:01:00Z",
  },
  {
    id: "like-9",
    userId: "user-2202",
    name: "江晚吟",
    avatar: "/static/assets/images/avatars/avatar-30.jpg",
    headline: "浙江大学 · 大3 · 烘焙达人",
    likedAt: "2026-05-13T12:02:00Z",
  },
  {
    id: "like-10",
    userId: "user-2203",
    name: "陆离",
    avatar: "/static/assets/images/avatars/avatar-31.jpg",
    headline: "南京大学 · 大4 · 桌游狂热",
    likedAt: "2026-05-12T13:03:00Z",
    verificationBadgeLevel: "school"
  },
  {
    id: "like-11",
    userId: "user-2204",
    name: "温言",
    avatar: "/static/assets/images/avatars/avatar-32.jpg",
    headline: "武汉大学 · 大1 · 猫奴",
    likedAt: "2026-05-11T14:04:00Z",
  },
  {
    id: "like-12",
    userId: "user-2205",
    name: "白夜",
    avatar: "/static/assets/images/avatars/avatar-33.jpg",
    headline: "四川大学 · 大2 · 旅行博主",
    likedAt: "2026-05-10T15:05:00Z",
  },
  {
    id: "like-13",
    userId: "user-2206",
    name: "许清欢",
    avatar: "/static/assets/images/avatars/avatar-34.jpg",
    headline: "厦门大学 · 大3 · 图书馆常客",
    likedAt: "2026-05-09T16:06:00Z",
    verificationBadgeLevel: "school"
  },
  {
    id: "like-14",
    userId: "user-2207",
    name: "顾北辰",
    avatar: "/static/assets/images/avatars/avatar-35.jpg",
    headline: "天津大学 · 大4 · 吉他手",
    likedAt: "2026-05-08T17:07:00Z",
  },
  {
    id: "like-15",
    userId: "user-2208",
    name: "林晚",
    avatar: "/static/assets/images/avatars/avatar-36.jpg",
    headline: "中南大学 · 大1 · 羽毛球",
    likedAt: "2026-05-07T18:08:00Z",
  },
  {
    id: "like-16",
    userId: "user-2209",
    name: "沈知微",
    avatar: "/static/assets/images/avatars/avatar-37.jpg",
    headline: "大连理工 · 大2 · 瑜伽",
    likedAt: "2026-05-06T19:09:00Z",
    verificationBadgeLevel: "school"
  },
  {
    id: "like-17",
    userId: "user-2210",
    name: "苏黎",
    avatar: "/static/assets/images/avatars/avatar-38.jpg",
    headline: "重庆大学 · 大3 · 钢琴",
    likedAt: "2026-05-15T20:10:00Z",
  },
  {
    id: "like-18",
    userId: "user-2211",
    name: "周子衿",
    avatar: "/static/assets/images/avatars/avatar-39.jpg",
    headline: "西安交大 · 大4 · 话剧社",
    likedAt: "2026-05-14T21:11:00Z",
  },
  {
    id: "like-19",
    userId: "user-2212",
    name: "陆时寒",
    avatar: "/static/assets/images/avatars/avatar-40.jpg",
    headline: "中国人民大学 · 大1 · 羽毛球",
    likedAt: "2026-05-13T10:12:00Z",
    verificationBadgeLevel: "school"
  },
  {
    id: "like-20",
    userId: "user-2213",
    name: "叶青梧",
    avatar: "/static/assets/images/avatars/avatar-41.jpg",
    headline: "北京师范 · 大2 · 咖啡控",
    likedAt: "2026-05-12T11:13:00Z",
  },
  {
    id: "like-21",
    userId: "user-2214",
    name: "江疏影",
    avatar: "/static/assets/images/avatars/avatar-42.jpg",
    headline: "上海交大 · 大3 · 动漫宅",
    likedAt: "2026-05-11T12:14:00Z",
  },
  {
    id: "like-22",
    userId: "user-2215",
    name: "顾南烟",
    avatar: "/static/assets/images/avatars/avatar-43.jpg",
    headline: "同济大学 · 大4 · 登山队",
    likedAt: "2026-05-10T13:15:00Z",
    verificationBadgeLevel: "school"
  },
  {
    id: "like-23",
    userId: "user-2216",
    name: "林夕",
    avatar: "/static/assets/images/avatars/avatar-44.jpg",
    headline: "中山大学 · 大1 · 摄影爱好者",
    likedAt: "2026-05-09T14:16:00Z",
  },
  {
    id: "like-24",
    userId: "user-2217",
    name: "陈默",
    avatar: "/static/assets/images/avatars/avatar-45.jpg",
    headline: "华南理工 · 大2 · 喜欢夜跑",
    likedAt: "2026-05-08T15:17:00Z",
  },
];

export const mockVisitors: VisitorRecord[] = [
  {
    id: "visit-1",
    userId: "user-2003",
    name: "苏晴",
    avatar: "/static/assets/images/avatars/avatar-32.jpg",
    headline: "中山大学 · 大一 · 摄影爱好者",
    visitedAt: "2026-05-20T16:45:00Z",
    isNew: true,
    verificationBadgeLevel: "school",
  },
  {
    id: "visit-2",
    userId: "user-2005",
    name: "顾言",
    avatar: "/static/assets/images/avatars/avatar-33.jpg",
    headline: "星海音乐 · 大二 · 音乐社",
    visitedAt: "2026-05-19T08:00:00Z",
    isNew: false,
  },
  {
    id: "visit-3",
    userId: "user-2008",
    name: "江晚吟",
    avatar: "/static/assets/images/avatars/avatar-34.jpg",
    headline: "华南师范 · 大一 · 舞蹈队",
    visitedAt: "2026-05-15T18:30:00Z",
    isNew: false,
    verificationBadgeLevel: "email",
  },
  {
    id: "visit-4",
    userId: "user-2300",
    name: "温言",
    avatar: "/static/assets/images/avatars/avatar-36.jpg",
    headline: "武汉大学 · 大1 · 猫奴",
    visitedAt: "2026-05-14T09:00:00Z",
    isNew: true,
  },
  {
    id: "visit-5",
    userId: "user-2301",
    name: "白夜",
    avatar: "/static/assets/images/avatars/avatar-37.jpg",
    headline: "四川大学 · 大2 · 旅行博主",
    visitedAt: "2026-05-13T10:01:00Z",
    isNew: false,
    verificationBadgeLevel: "email"
  },
  {
    id: "visit-6",
    userId: "user-2302",
    name: "许清欢",
    avatar: "/static/assets/images/avatars/avatar-38.jpg",
    headline: "厦门大学 · 大3 · 图书馆常客",
    visitedAt: "2026-05-12T11:02:00Z",
    isNew: false,
  },
  {
    id: "visit-7",
    userId: "user-2303",
    name: "顾北辰",
    avatar: "/static/assets/images/avatars/avatar-39.jpg",
    headline: "天津大学 · 大4 · 吉他手",
    visitedAt: "2026-05-11T12:03:00Z",
    isNew: false,
  },
  {
    id: "visit-8",
    userId: "user-2304",
    name: "林晚",
    avatar: "/static/assets/images/avatars/avatar-40.jpg",
    headline: "中南大学 · 大1 · 羽毛球",
    visitedAt: "2026-05-10T13:04:00Z",
    isNew: false,
  },
  {
    id: "visit-9",
    userId: "user-2305",
    name: "沈知微",
    avatar: "/static/assets/images/avatars/avatar-41.jpg",
    headline: "大连理工 · 大2 · 瑜伽",
    visitedAt: "2026-05-09T14:05:00Z",
    isNew: true,
    verificationBadgeLevel: "email"
  },
  {
    id: "visit-10",
    userId: "user-2306",
    name: "苏黎",
    avatar: "/static/assets/images/avatars/avatar-42.jpg",
    headline: "重庆大学 · 大3 · 钢琴",
    visitedAt: "2026-05-08T15:06:00Z",
    isNew: false,
  },
  {
    id: "visit-11",
    userId: "user-2307",
    name: "周子衿",
    avatar: "/static/assets/images/avatars/avatar-43.jpg",
    headline: "西安交大 · 大4 · 话剧社",
    visitedAt: "2026-05-07T16:07:00Z",
    isNew: false,
  },
  {
    id: "visit-12",
    userId: "user-2308",
    name: "陆时寒",
    avatar: "/static/assets/images/avatars/avatar-44.jpg",
    headline: "中国人民大学 · 大1 · 羽毛球",
    visitedAt: "2026-05-06T17:08:00Z",
    isNew: false,
  },
  {
    id: "visit-13",
    userId: "user-2309",
    name: "叶青梧",
    avatar: "/static/assets/images/avatars/avatar-45.jpg",
    headline: "北京师范 · 大2 · 咖啡控",
    visitedAt: "2026-05-05T18:09:00Z",
    isNew: false,
    verificationBadgeLevel: "email"
  },
  {
    id: "visit-14",
    userId: "user-2310",
    name: "江疏影",
    avatar: "/static/assets/images/avatars/avatar-46.jpg",
    headline: "上海交大 · 大3 · 动漫宅",
    visitedAt: "2026-05-14T19:10:00Z",
    isNew: true,
  },
  {
    id: "visit-15",
    userId: "user-2311",
    name: "顾南烟",
    avatar: "/static/assets/images/avatars/avatar-47.jpg",
    headline: "同济大学 · 大4 · 登山队",
    visitedAt: "2026-05-13T20:11:00Z",
    isNew: false,
  },
  {
    id: "visit-16",
    userId: "user-2312",
    name: "林夕",
    avatar: "/static/assets/images/avatars/avatar-48.jpg",
    headline: "中山大学 · 大1 · 摄影爱好者",
    visitedAt: "2026-05-12T21:12:00Z",
    isNew: false,
  },
  {
    id: "visit-17",
    userId: "user-2313",
    name: "陈默",
    avatar: "/static/assets/images/avatars/avatar-49.jpg",
    headline: "华南理工 · 大2 · 喜欢夜跑",
    visitedAt: "2026-05-11T09:13:00Z",
    isNew: false,
    verificationBadgeLevel: "email"
  },
  {
    id: "visit-18",
    userId: "user-2314",
    name: "顾言",
    avatar: "/static/assets/images/avatars/avatar-28.jpg",
    headline: "暨南大学 · 大3 · 文学系",
    visitedAt: "2026-05-10T10:14:00Z",
    isNew: false,
  },
  {
    id: "visit-19",
    userId: "user-2315",
    name: "夏言",
    avatar: "/static/assets/images/avatars/avatar-29.jpg",
    headline: "广东工业 · 大4 · 篮球队",
    visitedAt: "2026-05-09T11:15:00Z",
    isNew: true,
  },
  {
    id: "visit-20",
    userId: "user-2316",
    name: "苏晴",
    avatar: "/static/assets/images/avatars/avatar-30.jpg",
    headline: "星海音乐 · 大1 · 音乐社",
    visitedAt: "2026-05-08T12:16:00Z",
    isNew: false,
  },
  {
    id: "visit-21",
    userId: "user-2317",
    name: "周然",
    avatar: "/static/assets/images/avatars/avatar-31.jpg",
    headline: "华南师范 · 大2 · 舞蹈队",
    visitedAt: "2026-05-07T13:17:00Z",
    isNew: false,
    verificationBadgeLevel: "email"
  },
  {
    id: "visit-22",
    userId: "user-2318",
    name: "叶知秋",
    avatar: "/static/assets/images/avatars/avatar-32.jpg",
    headline: "北京大学 · 大3 · 自习搭子",
    visitedAt: "2026-05-06T14:18:00Z",
    isNew: false,
  },
];

export const mockHeartSignals: HeartSignal[] = [
  {
    id: "signal-1",
    fromUserId: "user-2003",
    fromUserName: "苏晴",
    fromUserAvatar: "/static/default-avatar.png",
    toUserId: "user-1001",
    status: "pending",
    sentAt: "2026-05-20T16:45:00Z",
    expiresAt: "2026-05-21T16:45:00Z",
  },
  {
    id: "signal-2",
    fromUserId: "user-2006",
    fromUserName: "叶知秋",
    fromUserAvatar: "/static/default-avatar.png",
    toUserId: "user-1001",
    status: "pending",
    sentAt: "2026-05-17T20:10:00Z",
    expiresAt: "2026-05-18T20:10:00Z",
  },
];
