# R11 Phase2 tour (generated by tmp/r11_tour_gen.py) — args: identity=A|B segment=1..4
$ErrorActionPreference = "Continue"
$wi = "D:\微信开发者\微信web开发者工具\wechatide.cmd"
$proj = "D:\6\恋爱小程序"
$ident = $args[0]
$segment = [int]$args[1]
$stamp = $env:R11_STAMP
$shots = "D:\6\恋爱小程序\reports\screenshots\r11-acceptance"
$tokfile = "D:\6\恋爱小程序\tmp_r11_login.json"
if ($ident -eq "B") { $tokfile = "D:\6\恋爱小程序\tmp_r11_guest.json" }
New-Item -ItemType Directory -Force -Path $shots | Out-Null

function WiRaw([string[]]$argList) { return (& $wi @argList 2>&1 | Out-String) }

# --- anti-freeze refresh at segment start ---
$null = WiRaw @("-c","ZCode","simulator_refresh","--project",$proj)
Start-Sleep -Seconds 10

# --- identity bootstrap: storage token + in-app session bootstrap ---
$token = (Get-Content $tokfile -Raw | ConvertFrom-Json).token
$jsBoot = 'function(){ try { wx.setStorageSync(''token'', '''' + $token + ''''); var app=getApp(); var vm=app[''$vm'']; var gp=(vm.$&&vm.$.appContext.config.globalProperties)||{}; var p=vm[''$pinia'']||gp[''$pinia'']; var s=p._s.get(''session''); if(s&&s.bootstrap){ s.bootstrap(); } return ''boot-ok''; } catch(e){ return ''ERR ''+e.message; } }'
$null = WiRaw @("-c","ZCode","automation_evaluate","--project",$proj,"--fn-source",$jsBoot)
Start-Sleep -Seconds 6
# R12-IND-GLOBAL-001: boot must be verified (retry once if session not established)
$jsVerify = 'function(){ try { var app=getApp(); var vm=app[''$vm'']; var gp=(vm.$&&vm.$.appContext.config.globalProperties)||{}; var p=vm[''$pinia'']||gp[''$pinia'']; var s=p._s.get(''session''); return s && s.isLoggedIn ? ''logged-in'' : ''not-logged-in''; } catch(e){ return ''ERR''; } }'
$vraw = WiRaw @("-c","ZCode","automation_evaluate","--project",$proj,"--fn-source",$jsVerify)
if ($vraw -notmatch 'logged-in') {
  Write-Host "  [boot] session NOT established - retrying" -ForegroundColor Yellow
  Start-Sleep -Seconds 4
  $null = WiRaw @("-c","ZCode","automation_evaluate","--project",$proj,"--fn-source",$jsBoot)
  Start-Sleep -Seconds 6
  $vraw = WiRaw @("-c","ZCode","automation_evaluate","--project",$proj,"--fn-source",$jsVerify)
}
$bootLine = "boot[{0}]: {1}" -f $ident, $(if ($vraw -match 'logged-in') {"ok"} else {"FAILED"})
Add-Content -Path (Join-Path $shots ("boot-verify-{0}.log" -f $ident)) -Value $bootLine -Encoding UTF8
Write-Host $bootLine

$rows = @(
  "1|/pages/login/index|pages_login_index"
  "1|/pages/home/index|pages_home_index"
  "1|/subpackages/village/village/index|subpackages_village_village_index"
  "1|/subpackages/village/village/tag-posts?tagName=%E6%91%84%E5%BD%B1|subpackages_village_village_tag-posts"
  "1|/subpackages/circles/circles/topic-detail?id=37|subpackages_circles_circles_topic-detail"
  "1|/subpackages/campus/campus/index|subpackages_campus_campus_index"
  "1|/subpackages/discover-extra/discover/matching?target=10003|subpackages_discover-extra_discover_matching"
  "1|/subpackages/discover-extra/discover/history|subpackages_discover-extra_discover_history"
  "1|/subpackages/tools/love-center/index|subpackages_tools_love-center_index"
  "1|/subpackages/tools/heart-signals/index|subpackages_tools_heart-signals_index"
  "1|/subpackages/tools/love-center/consulting|subpackages_tools_love-center_consulting"
  "1|/subpackages/profile-extra/profile/visitors|subpackages_profile-extra_profile_visitors"
  "1|/subpackages/profile-extra/profile/album|subpackages_profile-extra_profile_album"
  "1|/subpackages/profile-extra/feedback/history|subpackages_profile-extra_feedback_history"
  "1|/subpackages/setup/campus/index|subpackages_setup_campus_index"
  "1|/subpackages/setup/showcase/index|subpackages_setup_showcase_index"
  "1|/subpackages/legal/privacy/index|subpackages_legal_privacy_index"
  "1|/subpackages/market/wallet/index|subpackages_market_wallet_index"
  "2|/pages/register/index|pages_register_index"
  "2|/pages/nearby/index|pages_nearby_index"
  "2|/subpackages/village/village/publish|subpackages_village_village_publish"
  "2|/subpackages/village/village/history|subpackages_village_village_history"
  "2|/subpackages/circles/circles/post-topic?circleId=8|subpackages_circles_circles_post-topic"
  "2|/subpackages/campus/campus/post-topic|subpackages_campus_campus_post-topic"
  "2|/subpackages/discover-extra/discover/match-success|subpackages_discover-extra_discover_match-success"
  "2|/subpackages/discover-extra/likes/index|subpackages_discover-extra_likes_index"
  "2|/subpackages/tools/help/index|subpackages_tools_help_index"
  "2|/subpackages/tools/activities/detail?id=11|subpackages_tools_activities_detail"
  "2|/subpackages/profile-extra/settings/index|subpackages_profile-extra_settings_index"
  "2|/subpackages/profile-extra/profile/other?userId=100152|subpackages_profile-extra_profile_other"
  "2|/subpackages/profile-extra/profile/favorites|subpackages_profile-extra_profile_favorites"
  "2|/subpackages/chat/chat-session/index?userId=10003|subpackages_chat_chat-session_index"
  "2|/subpackages/setup/schedule/index|subpackages_setup_schedule_index"
  "2|/subpackages/support/feedback/index|subpackages_support_feedback_index"
  "2|/subpackages/legal/agreement/index|subpackages_legal_agreement_index"
  "2|/subpackages/vip/index|subpackages_vip_index"
  "3|/pages/register/success|pages_register_success"
  "3|/pages/messages/index|pages_messages_index"
  "3|/subpackages/village/village/post?id=225|subpackages_village_village_post"
  "3|/subpackages/circles/circles/index|subpackages_circles_circles_index"
  "3|/subpackages/circles/circles/circle-home?circleId=8|subpackages_circles_circles_circle-home"
  "3|/subpackages/campus/campus/topic-detail?id=153|subpackages_campus_campus_topic-detail"
  "3|/subpackages/discover-extra/home/segment|subpackages_discover-extra_home_segment"
  "3|/subpackages/discover-extra/likes-visitors/index|subpackages_discover-extra_likes-visitors_index"
  "3|/subpackages/tools/security/index|subpackages_tools_security_index"
  "3|/subpackages/tools/love-center/nearby|subpackages_tools_love-center_nearby"
  "3|/subpackages/profile-extra/verification/index|subpackages_profile-extra_verification_index"
  "3|/subpackages/profile-extra/profile/location|subpackages_profile-extra_profile_location"
  "3|/subpackages/profile-extra/profile/tasks|subpackages_profile-extra_profile_tasks"
  "3|/subpackages/chat/official-chat/index|subpackages_chat_official-chat_index"
  "3|/subpackages/setup/recommend-pref/index|subpackages_setup_recommend-pref_index"
  "3|/subpackages/discover/discussions/index|subpackages_discover_discussions_index"
  "3|/subpackages/market/detail/index?id=1|subpackages_market_detail_index"
  "3|/subpackages/vip/promo-code|subpackages_vip_promo-code"
  "4|/pages/discover/index|pages_discover_index"
  "4|/pages/profile/index|pages_profile_index"
  "4|/subpackages/village/village/detail?id=225|subpackages_village_village_detail"
  "4|/subpackages/circles/circles/topics|subpackages_circles_circles_topics"
  "4|/subpackages/campus/campus/hub|subpackages_campus_campus_hub"
  "4|/subpackages/campus/campus/certification|subpackages_campus_campus_certification"
  "4|/subpackages/discover-extra/nearby/people|subpackages_discover-extra_nearby_people"
  "4|/subpackages/tools/daily-question/index|subpackages_tools_daily-question_index"
  "4|/subpackages/tools/search/index|subpackages_tools_search_index"
  "4|/subpackages/tools/love-center/mbti|subpackages_tools_love-center_mbti"
  "4|/subpackages/profile-extra/verification/real-name|subpackages_profile-extra_verification_real-name"
  "4|/subpackages/profile-extra/profile/privacy|subpackages_profile-extra_profile_privacy"
  "4|/subpackages/profile-extra/settings/dnd|subpackages_profile-extra_settings_dnd"
  "4|/subpackages/setup/profile/index|subpackages_setup_profile_index"
  "4|/subpackages/setup/interest/index|subpackages_setup_interest_index"
  "4|/subpackages/discover/activities/index|subpackages_discover_activities_index"
  "4|/subpackages/market/shop/index|subpackages_market_shop_index"
  "4|/subpackages/vip/bills|subpackages_vip_bills"
)

foreach ($row in $rows) {
  $parts = $row.Split("|")
  $seg = [int]$parts[0]
  if ($seg -ne $segment) { continue }
  $url = $parts[1]
  $name = $parts[2]
  $file = Join-Path $shots ("{0}-{1}-{2}.png" -f $ident, $stamp, $name)
  $navJs = 'function(){ wx.reLaunch({ url: ''' + $url + ''', fail: function(e){ console.error(''NAV_FAIL '' + $name + '' '' + JSON.stringify(e)); } }); return 1; }'
  $null = WiRaw @("-c","ZCode","automation_evaluate","--project",$proj,"--fn-source",$navJs)
  Start-Sleep -Seconds 6
  $null = WiRaw @("-c","ZCode","simulator_screenshot","--project",$proj,"--path",$file)
  Start-Sleep -Seconds 2
  $file2 = Join-Path $shots ("{0}-{1}-{2}.b.png" -f $ident, $stamp, $name)
  $null = WiRaw @("-c","ZCode","simulator_screenshot","--project",$proj,"--path",$file2)
  $cerr = WiRaw @("-c","ZCode","get_simulator_console","--project",$proj,"--command","grep -iE 'NAV_FAIL|TypeError|is not defined' | tail -4")
  $status = "clean"
  if ($cerr -match 'NAV_FAIL|TypeError|is not defined') {
    $status = "ISSUE"
    Add-Content -Path (Join-Path $shots ("console-issues-{0}.log" -f $ident)) -Value ("### [{0}] {1}" -f $name, $cerr) -Encoding UTF8
    Write-Host ("  [console] {0}" -f $name) -ForegroundColor Yellow
  }
  # R12-IND-EVIDENCE-001: console evidence per page always recorded
  Add-Content -Path (Join-Path $shots ("console-evidence-{0}.log" -f $ident)) -Value ("{0}`t{1}" -f $name, $status) -Encoding UTF8
  Write-Host ("  ok {0} ({1})" -f $name, $status)
}
Write-Host ("TOUR DONE identity={0} segment={1}" -f $ident, $segment)
